server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: notification-service
  config:
    import: "${SPRING_CONFIG_IMPORT:optional:configserver:http://localhost:8888}"
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb+srv://gihanvidu:199884@ecanotificationdb.6lmcpdk.mongodb.net/ecanotificationdb?retryWrites=true&w=majority}
      database: ecanotificationdb

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:9001/eureka/}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always